spring.application.name=fleet.simulator


spring.kafka.bootstrap-servers=${KAFKA_URL}


# =========================
# PRODUCER
# simulator -> Kafka
# =========================

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# wysy?amy typ w headerze Kafka
spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.producer.properties.spring.json.type.mapping=\
truck:com.damianos.fleet.simulator.model.Truck,\
event:com.damianos.fleet.simulator.model.TruckEvent


# =========================
# CONSUMER
# Kafka -> simulator
# =========================

spring.kafka.consumer.group-id=simulator
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


spring.kafka.consumer.properties.spring.json.trusted.packages=*

# korzystamy z headerów Kafka
spring.kafka.consumer.properties.spring.json.use.type.headers=true


# mapowanie nazw z headerów -> klasy simulatora
spring.kafka.consumer.properties.spring.json.type.mapping=\
com.damianos.fleet.vehicletracking.model.Command:com.damianos.fleet.simulator.model.Command


server.port=8060
backend.url=${BACKEND_URL:http://localhost:8090}