spring.application.name=vehicletracking

server.port=${SERVER_PORT:8090}


# OSRM
osrm.host=${OSRM_HOST}
osrm.url=${OSRM_URL}


# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Actuator
management.endpoints.web.exposure.include=health,metrics


# JVM
spring.jvm.options=${JVM_OPTIONS:-Xmx1024m}


# Elasticsearch
spring.elasticsearch.uris=${ELASTICSEARCH_URL}